// eslint-disable-next-line import/prefer-default-export
export const UPDATE_PROJECT_CATEGORY = 'UPDATE_PROJECT_CATEGORY';
export const GET_SELECTED_PROJECT_ADDRESS = 'GET_SELECTED_PROJECT_ADDRESS';
export const IS_DEPOSITED = 'IS_DEPOSITED';
export const GET_DEPLOY_STATE = 'GET_DEPLOY_STATE';
export const GET_PROJECT_FOUNDER = 'GET_PROJECT_FOUNDER';
export const GET_SELECTED_TASK = 'GET_SELECTED_TASK';
export const SET_REJECTED_BUILDER = 'SET_REJECTED_BUILDER';
export const SET_ACCEPTED_BUILDER = 'SET_ACCEPTED_BUILDER';
