export const UPDATE_LOGIN_STEP = 'UPDATE_LOGIN_STEP';
export const UPDATE_FIRST_TIME_USER = 'UPDATE_FIRST_TIME_USER';
export const UPDATE_CURRENT_SIGN_UP_STEP = 'UPDATE_CURRENT_SIGN_UP_STEP';
export const UPDATE_ARCANA_AUTH_ADDRESS = 'UPDATE_ARCANA_AUTH_ADDRESS';
export const UPDATE_SIGNUP_STEP = 'UPDATE_SIGNUP_STEP';
