export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const GET_WALLET_ADDRESS = 'GET_WALLET_ADDRESS';
export const GET_WALLET_USDC_BALANCE = 'GET_WALLET_USDC_BALANCE';
export const UPDATE_USER_DISCORD = 'UPDATE_USER_DISCORD';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const SIGN_UP_STEP = 'SIGN_UP_STEP';
export const UPDATE_USER_ID = 'UPDATE_USER_ID';
