import A from 'assets/images/alphabets/A.png';
import B from 'assets/images/alphabets/B.png';
import C from 'assets/images/alphabets/C.png';
import D from 'assets/images/alphabets/D.png';
import E from 'assets/images/alphabets/E.png';
import F from 'assets/images/alphabets/F.png';
import G from 'assets/images/alphabets/G.png';
import H from 'assets/images/alphabets/H.png';
import I from 'assets/images/alphabets/I.png';
import J from 'assets/images/alphabets/J.png';
import K from 'assets/images/alphabets/K.png';
import L from 'assets/images/alphabets/L.png';
import M from 'assets/images/alphabets/M.png';
import N from 'assets/images/alphabets/N.png';
import O from 'assets/images/alphabets/O.png';
import P from 'assets/images/alphabets/P.png';
import Q from 'assets/images/alphabets/Q.png';
import R from 'assets/images/alphabets/R.png';
import S from 'assets/images/alphabets/S.png';
import T from 'assets/images/alphabets/T.png';
import U from 'assets/images/alphabets/U.png';
import V from 'assets/images/alphabets/V.png';
import W from 'assets/images/alphabets/W.png';
import X from 'assets/images/alphabets/X.png';
import Y from 'assets/images/alphabets/Y.png';
import Z from 'assets/images/alphabets/Z.png';

const getDefaultAvatarSrc = (alphabet?: string) => {
  if (alphabet === 'A') return A;
  if (alphabet === 'B') return B;
  if (alphabet === 'C') return C;
  if (alphabet === 'D') return D;
  if (alphabet === 'E') return E;
  if (alphabet === 'F') return F;
  if (alphabet === 'G') return G;
  if (alphabet === 'H') return H;
  if (alphabet === 'I') return I;
  if (alphabet === 'J') return J;
  if (alphabet === 'K') return K;
  if (alphabet === 'L') return L;
  if (alphabet === 'M') return M;
  if (alphabet === 'N') return N;
  if (alphabet === 'O') return O;
  if (alphabet === 'P') return P;
  if (alphabet === 'Q') return Q;
  if (alphabet === 'R') return R;
  if (alphabet === 'S') return S;
  if (alphabet === 'T') return T;
  if (alphabet === 'U') return U;
  if (alphabet === 'V') return V;
  if (alphabet === 'W') return W;
  if (alphabet === 'X') return X;
  if (alphabet === 'Y') return Y;
  if (alphabet === 'Z') return Z;
  return A;
};

export default getDefaultAvatarSrc;
