export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_USER_XP = 'GET_USER_XP';
export const GET_USDC_BALANCE = 'GET_USDC_BALANCE';
export const GET_PROFILE_CONTRACT_ADDRESS = 'GET_PROFILE_CONTRACT_ADDRESS';
