export const FILL_PROFILE_DATA = 'FILL_PROFILE_DATA';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const ADD_PROFILE_WORKPLACE = 'ADD_PROFILE_WORKPLACE';
export const REMOVE_PROFILE_WORKPLACE = 'REMOVE_PROFILE_WORKPLACE';
export const UPDATE_PROFILE_WORKPLACE = 'UPDATE_PROFILE_WORKPLACE';
export const UPDATE_PROFILE_DETAILS = 'UPDATE_PROFILE_DETAILS';
export const GET_USER_XP = 'GET_USER_XP';
export const GET_USDC_BALANCE = 'GET_USDC_BALANCE';
export const GET_PROFILE_CONTRACT_ADDRESS = 'GET_PROFILE_CONTRACT_ADDRESS';
export const UPDATE_PROFILE_CONTRACT_ADDRESS =
  'UPDATE_PROFILE_CONTRACT_ADDRESS';
export const SET_CURRENT_USER_PROFILE_PICTURE =
  'SET_CURRENT_USER_PROFILE_PICTURE';
