export const FILL_PROFILE_DATA = 'FILL_PROFILE_DATA';
export const ADD_PROFILE_SKILL = 'ADD_PROFILE_SKILL';
export const REMOVE_PROFILE_SKILL = 'REMOVE_PROFILE_SKILL';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const UPDATE_PROFILE_SOCIALS = 'UPDATE_PROFILE_SOCIALS';
